### ISSUE TITLE
Vision Statement -- Project Description

### ISSUE THREAD

**Issue by jmorgancusick** [jmcusick/currencyhft#4]
The vision statement should include an executive summary of the project (6 points), including a problem/solution statement

James, Is the problem/solution statement going in this section? I'm not sure how Project Description subsection in the google doc aligns with the rubric. Thanks!

**Comment by james-nakashian** [comment]
Yes, this section has the executive summary and problem/solution statement.
I structured it this way to follow the example Inception document.

**Comment by jmorgancusick** [comment]
Great, thank you @james-nakashian, I had not seen the example document. I just added links to the [inception example doc](https://drive.google.com/file/d/0B0dykRFd8lH8ZXFhNFF6RW5VeGc/view) and the [inception grading criteria](https://docs.google.com/document/d/1JNpd9yGUbbiirn1-oUSZdHfaH24_TKmZst11MeVyYH0/edit#) to the [description of the inception milestone](https://github.com/jmcusick/currencyhft/milestone/1)

**Comment by james-nakashian** [comment]
Vision Statement was completed
