### ISSUE TITLE
Use Case -- OpenForexDashboard

### ISSUE THREAD

**Issue by jmorgancusick** [jmcusick/currencyhft#43]
User wants to do research on a specific ticker in the forex market

**Comment by james-nakashian** [comment]
@jmcusick Try to follow the style I used for FindProfitableTrends and UpdateData
Also fill in F10 and F11 in the Functionality Requirements section and UC5 in Work Breakdown Schedule

**Comment by jmorgancusick** [comment]
@james-nakashian thank you for the instruction, made it easy to work through. Do we need to assign individuals pieces of the work breakdown structure?

I have filled in the OpenForexDashboard, F10, F11 and UC5. Leaving issue open for discussion and edits.

**Comment by jmorgancusick** [comment]
Completed as of 76cb6228819d1ba71a397458288421be5deb7402.
