### ISSUE TITLE
Add endpoints to API for Dashboard

### ISSUE THREAD

**Issue by YushYush** [jmcusick/currencyhft#49]
Dashboard Endpoints:
- [x] Stock Tickers 
- [x] Start Currency and End Currency 
- [x] updates to query.cpp
- [x] updates to app.js

- [x] Test

**Comment by jmorgancusick** [comment]
* [app.js](https://github.com/jmcusick/currencyhft/blob/master/node/app.js) file is where the endpoints are in the node server. Can start off calling some nonexistent c++ function.

* c++ function will go in [query.cpp](https://github.com/jmcusick/currencyhft/blob/master/node/src/query.cpp)

* the c++ function will need to call a database function in [api.h](https://github.com/jmcusick/currencyhft/blob/master/node/src/sql/api.h)

**Comment by jmorgancusick** [comment]
* frontend sends ajax call to the endpoint (see [query.js](https://github.com/jmcusick/currencyhft/blob/master/node/public/scripts/query.js))

**Comment by cordom2** [comment]
The endpoint functionality on the back-end should be working now. Now we just need the front-end portion to connect it.

**Comment by jmorgancusick** [comment]
Completed as of 9f50bf84c897a175f0b6d6e923c963d0b89a8f2b.
