### ISSUE TITLE
Research and select JavaScript library for dashboard charts

### ISSUE THREAD

**Issue by YushYush** [jmcusick/currencyhft#50]

**Comment by jmorgancusick** [comment]
"Chart" refers to an x-y plot

"Graph" refers to a tree structure with nodes and edges.

For this issue, select a javascript library to aid in implementing historical stock market data charts.

For [example](https://finance.yahoo.com/chart/EURUSD%3DX?p=EURUSD%3DX#eyJtdWx0aUNvbG9yTGluZSI6ZmFsc2UsImJvbGxpbmdlclVwcGVyQ29sb3IiOiIjZTIwMDgxIiwiYm9sbGluZ2VyTG93ZXJDb2xvciI6IiM5NTUyZmYiLCJtZmlMaW5lQ29sb3IiOiIjNDVlM2ZmIiwibWFjZERpdmVyZ2VuY2VDb2xvciI6IiNmZjdiMTIiLCJtYWNkTWFjZENvbG9yIjoiIzc4N2Q4MiIsIm1hY2RTaWduYWxDb2xvciI6IiMwMDAwMDAiLCJyc2lMaW5lQ29sb3IiOiIjZmZiNzAwIiwic3RvY2hLTGluZUNvbG9yIjoiI2ZmYjcwMCIsInN0b2NoRExpbmVDb2xvciI6IiM0NWUzZmYiLCJyYW5nZSI6IjF5In0%3D)
