### ISSUE TITLE
Create and test shortest path algorithm

### ISSUE THREAD

**Issue by jmorgancusick** [jmcusick/currencyhft#54]
Select an algorithm for shortest path algorithm. Actually writing a test example may be a good way to do this. Could provide insights and the data structure (presumably the adjacency matrix that we discussed) could be used as a boilerplate for later.

**Comment by pengelsman7** [comment]
changed title since it was moved to iteration 3, so it now reflects what is to be done by the end of this iteration

**Comment by jmorgancusick** [comment]
See [algo](https://github.com/jmcusick/currencyhft/tree/algo) branch
