### ISSUE TITLE
Forex Dashboard Front-End buttons which display endpoint's return

### ISSUE THREAD

**Issue by jmorgancusick** [jmcusick/currencyhft#57]

**Comment by cordom2** [comment]
I finished the endpoints buttons on the back-end section

**Comment by YushYush** [comment]
@cordom2 this issue is pertaining to rendering and front-end dev. API endpoints dev is encompassed in issue: #49

**Comment by jmorgancusick** [comment]
Inhibiting bug: #67

**Comment by YushYush** [comment]
resolved as of 83b55ed77c6dd9e9c87992e44fa063a4de4224d2
