### ISSUE TITLE
User Scenarios -- Persona Two

### ISSUE THREAD

**Issue by jmorgancusick** [jmcusick/currencyhft#6]
The User Scenario should create a realistic picture of a persona using the software.  Look for details about the Persona (10 points) and the User Interface (10 points).  We are looking for specifics of what the persona is actually doing in the interface to achieve their goal.  Also how specifically does the interface respond? Did the Persona achieve their goal? (8 points)  Was the User Scenario compelling? (7 points)  Is the picture painted realistic and detailed? (7 points)

Persona 2 is the currency trader investigated arbitrage opportunities in historical and current currency exchange marketplaces.

**Comment by YushYush** [comment]
finished as of bbd3ddd5df6b842b9ac6a5361b09662d1cecefba
