### ISSUE TITLE
Forex Continuous Updating (Daily)

### ISSUE THREAD

**Issue by jmorgancusick** [jmcusick/currencyhft#61]
Continuously scrape forex data (1 day, 1 minute intervals). Pull the previous day's data (not the current days).

**Comment by pengelsman7** [comment]
The daily updater is set up to update forex, forexDashDaily, and forexDashMinute every day at 12:01 am.  Git commit 8083a4e2d7e3197d993d59866bdb46761810e6b4

**Comment by pengelsman7** [comment]
The daily updater is set up to update forex, forexDashDaily, and forexDashMinute every day at 12:01 am.  Git commit 8083a4e2d7e3197d993d59866bdb46761810e6b4
