### ISSUE TITLE
tickerData endpoint only returns 16 values not 18

### ISSUE THREAD

**Issue by jmorgancusick** [jmcusick/currencyhft#68]
Reference commit 6e3834d710154ed8b7f916fa2058f78d0e2af1ee.

Expected:

    "USDCAD=X", "EURJPY=X"
    "EURUSD=X", "EURCHF=X",
    "USDCHF=X", "EURGBP=X",
    "GBPUSD=X", "AUDCAD=X",
    "NZDUSD=X", "GBPCHF=X",
    "AUDUSD=X", "GBPJPY=X",
    "USDJPY=X", "CHFJPY=X",
    "EURCAD=X", "AUDJPY=X",
    "EURAUD=X", "AUDNZD=X"

Returned:

    [{"ticker":"USDJPY=X","percentChange":0},{"ticker":"USDCHF=X","percentChange":0
    {"ticker":"USDCAD=X","percentChange":0},{"ticker":"NZDUSD=X","percentChange":0},
    {"ticker":"AUDJPY=X","percentChange":0},{"ticker":"EURCHF=X","percentChange":0},
    {"ticker":"EURAUD=X","percentChange":0},{"ticker":"CHFJPY=X","percentChange":0},
    {"ticker":"EURGBP=X","percentChange":0},{"ticker":"AUDCAD=X","percentChange":0},
    {"ticker":"EURCAD=X","percentChange":0},{"ticker":"GBPCHF=X","percentChange":0},
    {"ticker":"GBPJPY=X","percentChange":0},{"ticker":"AUDUSD=X","percentChange":0},
    {"ticker":"GBPUSD=X","percentChange":0},{"ticker":"AUDNZD=X","percentChange":0}]

**Comment by pengelsman7** [comment]
you missed a comma after "EURJPY=X" in the code

**Comment by jmorgancusick** [comment]
Fixed missing comma in 3e6aa11417f5de071030975c755a83f55ecd3f7e.

**Comment by jmorgancusick** [comment]
The above fix did work, just hadn't pulled to branch
