### ISSUE TITLE
Arbitrage Page

### ISSUE THREAD

**Issue by jmorgancusick** [jmcusick/currencyhft#76]
Add frontend page to display profitability paths

- [x] Add drop down menus for start and end currencies 
- [x] Add drop down menu for currency exclusions 
- [x] Add drop down for limiting edges
- [x] Add api calls for arbitrageData
- [x] Display optimal rate conversion upon button press
- [x] Display optimal paths upon button press

**Comment by YushYush** [comment]
Closed as of 4646cf6860f966b3391f8bb0faef88a8b3faead2
