### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by jmorgancusick** [jmcusick/currencyhft#77]
Add frontend page for the calculator (separate page).  Conversion between two currencies is the primary feature.

- [x] Add drop down menus for start and end currencies 
- [x] Add api calls for calculatorData
- [x] Display rate conversion automatically

**Comment by YushYush** [comment]
Close as of 93e32a49d78acfd17036e48a93620f2ba4aee179 and 6db9b93b9ed735ba67f8d3eefc19b74796c4c4b9
